name: california_housing_env
channels:
  - defaults
dependencies:
dependencies:
  - python=3.11.6
  - scikit-learn=1.3.1
  - numpy=1.24.4
  - cloudpickle=3.0.0
  - lz4=4.3.2
  - psutil=5.9.5
  - pyyaml=6.0.1
  - scipy=1.14.1
  - pip
  - pip:
      - boto3
      - mlflow==2.9.1
      - fastapi==0.110.0
